CREATE DATABASE CLINICA_MEDICA
GO

USE CLINICA_MEDICA
GO

--DROP DATABASE CLINICA_MEDICA

CREATE TABLE PACIENTE(
	ID_PACIENTE INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	NOMBRE VARCHAR(80) NOT NULL,
	APELLIDO VARCHAR(80) NOT NULL,
	TELEFONO VARCHAR(11) NULL,
	FECHA_NAC DATE NOT NULL,
	DIRECCION VARCHAR(80) NULL,
	EMAIL  VARCHAR(20) NOT NULL,
	ACTIVO BIT DEFAULT 0
)
GO

CREATE TABLE MEDICO (
	ID_MEDICO INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	NOMBRE VARCHAR(80) NOT NULL,
	APELLIDO VARCHAR(80) NOT NULL,
	TELEFONO VARCHAR(11) NULL,
	FECHA_NAC DATE NOT NULL,
	DIRECCION VARCHAR(80) NULL,
	EMAIL  VARCHAR(20) NOT NULL,
	ESPECIALIDAD VARCHAR(30) CHECK(ESPECIALIDAD IN('GENERAL','PEDIATRÍA','OBSTETRICIA/GINECOLOGÍA',
	'INTERNA','CARDIOLOGÍA','OFTALMOLOGÍA','OTORRINOLARINGOLOGÍA','DERMATOLOGÍA')) NOT NULL,
	ACTIVO BIT DEFAULT 0
)
GO

CREATE TABLE RECEPCIONISTA (
	ID_RECEPCIONISTA INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	NOMBRE VARCHAR(80) NOT NULL,
	APELLIDO VARCHAR(80) NOT NULL,
	TELEFONO VARCHAR(11) NULL,
	FECHA_NAC DATE NOT NULL,
	DIRECCION VARCHAR(80) NULL,
	EMAIL VARCHAR(20) NOT NULL,
	ACTIVO BIT DEFAULT 0
)
GO

CREATE TABLE CITAS (
	ID_CITA INT IDENTITY PRIMARY KEY,
	ID_MEDICO INT NOT NULL FOREIGN KEY REFERENCES MEDICO(ID_MEDICO),
	ID_PACIENTE INT NOT NULL FOREIGN KEY REFERENCES PACIENTE(ID_PACIENTE),
	FECHA DATETIME NOT NULL,
	HORA TIME NOT NULL,
	ESPECIALIDAD VARCHAR(30) CHECK(ESPECIALIDAD IN('GENERAL','PEDIATRÍA','OBSTETRICIA/GINECOLOGÍA',
	'INTERNA','CARDIOLOGÍA','OFTALMOLOGÍA','OTORRINOLARINGOLOGÍA','DERMATOLOGÍA')) NOT NULL,
	CANCELADA BIT DEFAULT 0
)
GO

CREATE TABLE PAGOS(
ID_PAGOS INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
ID_PACIENTE INT NOT NULL FOREIGN KEY REFERENCES PACIENTE(ID_PACIENTE),
FECHA DATETIME NOT NULL,
MONTO INT NOT NULL,
DETALLE VARCHAR(55) NOT NULL,
CANCELADO BIT NOT NULL
)
GO 

CREATE TABLE HISTORIAL_MEDICO(
ID_HISTORIAL INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
ID_PACIENTE INT NOT NULL FOREIGN KEY REFERENCES PACIENTE(ID_PACIENTE),
ID_MEDICO INT NOT NULL FOREIGN KEY REFERENCES MEDICO(ID_MEDICO),
DIAGNOSTICOS VARCHAR(65) NOT NULL,
)
GO

CREATE TABLE MEDICAMENTOS(
ID_MEDICAMENTO INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
ID_HISTORIAL INT NOT NULL FOREIGN KEY REFERENCES HISTORIAL_MEDICO(ID_HISTORIAL),
ID_MEDICO INT NOT NULL FOREIGN KEY REFERENCES MEDICO(ID_MEDICO),
DOSIS VARCHAR(65) NOT NULL,
)
GO


CREATE PROCEDURE ELIMINAR
		@idpaciente int,  --recibe un id
		@msj varchar(50) out   --devuelve un mensaje
AS BEGIN
if (not exists(select * from PACIENTE where ID_PACIENTE=@idpaciente))
	begin
		set @msj='El paciente no existe'
		return 0
	end
else
	begin
		DELETE from PACIENTE where ID_PACIENTE=@idpaciente
		set @msj='Paciente eliminado'
		return 1
	end
END
GO